version: "3.8"
services:
  web:
    image: nlp:latest
    build:
      context: .
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_NAME=postgres
    entrypoint: ["/bin/bash", "-c", "source .venv/bin/activate && cd src/djangoproject && python manage.py migrate && gunicorn -w 4 -b 0.0.0.0:8080 nlp.wsgi:application"]
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
