version: "3.8"
services:
  web:
    build:
      context: .
    entrypoint: ["/bin/bash", "-c", "poetry run python manage.py migrate && gunicorn -w 4 -b 0.0.0.0:8080 nlp.wsgi:application"]
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgres
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_NAME=postgres
    ports:
      - "5432:5432"
