[tool.poetry]
name = "nlp"
version = "0.1.0"
description = "NLP"
authors = ["Miroslav Mlynarik <miroslav.mlynarik@gmail.com>"]

[tool.poetry.dependencies]
python = "3.9.5"
pandas = "^1.3"
sklearn = "^0.0"
gensim = "^4.1.2"
jupyterlab = "^3.2.4"
pycodestyle = "^2.8.0"
ipython = "^7.29.0"
seaborn = "^0.11.2"
pydantic = "^1.8.2"
python-dotenv = "^0.19.2"
pyLDAvis = "^3.3.1"
tqdm = "^4.62.3"
ipywidgets = "^7.6.5"
transformers = "^4.19.2"
torch = "^1.11.0"
plotly = "^5.8.0"
datasets = "^2.2.2"
nltk = "^3.7"
django = "^4.1.2"

[tool.poetry.group.dev.dependencies]
pycodestyle = "^2.9.1"
black = "^22.10.0"
pre-commit = "^2.20.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
