[tool.poetry]
name = "NLP"
version = "0.1.0"
description = "My NLP home projects"
license = "Proprietary"
authors = ["Miroslav Mlynarik <miroslav.mlynarik@gmail.com>"]
readme = "README.md"
repository = "https://github.com/mmlynarik/nlp"
keywords = ["nlp"]

[tool.poetry.dependencies]
python = ">=3.9.5,<3.11"
gensim = "4.1.2"
top2vec = "1.0.27"
pyLDAvis = "3.3.1"
django = "4.1.2"
gunicorn = "20.1"
psycopg2-binary = "2.9"
dj-database-url = "^1.2.0"
sentence-transformers = "2.2.2"
tensorflow = "2.9"
jupyterlab = "3.2.4"
ipython = "7.29.0"
ipywidgets = "7.6.5"
python-dotenv = "0.19.2"
python-dateutil = "2.8.2"
tqdm = "4.62.3"
click = "8.0.2"
datasets = "2.9.0"
torch = "2.0.0"
pandas = "2.0.1"
huggingface-download-cli = "1.0.3"
tokenizers = "0.13.3"
rouge = "1.0.1"
lightning = "2.0.3"
transformers = "4.30.2"
sentencepiece = "0.1.99"

[tool.poetry.group.dev.dependencies]
src = {path = "src", develop = true}
pycodestyle = "2.9.1"
black = "19.10b0"
pre-commit = "2.20.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 110
