[tool.poetry]
name = "NLP"
version = "0.1.0"
description = "My NLP home projects"
license = "Proprietary"
authors = ["Miroslav Mlynarik <miroslav.mlynarik@gmail.com>"]
readme = "README.md"
repository = "https://github.com/mmlynarik/nlp"
keywords = ["nlp"]

[tool.poetry.dependencies]
python = ">=3.9.5,<3.11"
pandas = "1.2"
gensim = "4.1.2"
top2vec = "^1.0.27"
pyLDAvis = "3.3.1"
django = "4.1.2"
gunicorn = "20.1"
psycopg2-binary = "2.9"
dj-database-url = "^1.2.0"

[tool.poetry.group.dev.dependencies]
src = {path = "src", develop = true}
tensorflow = "2.9"
jupyterlab = "3.2.4"
ipython = "7.29.0"
ipywidgets = "7.6.5"
python-dotenv = "0.19.2"
transformers = "4.19.2"
python-dateutil = "^2.8.2"
tqdm = "4.62.3"
click = "8.0.2"
datasets = "^2.9.0"
pycodestyle = "2.9.1"
black = "19.10b0"
pre-commit = "2.20.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 110

[mypy]
ignore_missing_imports = true
check_untyped_defs = true
strict_equality = false
