# Generated by Django 4.1.2 on 2022-10-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OKRAReviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("title", models.CharField(max_length=512)),
                ("text", models.CharField(max_length=10000)),
                ("url", models.CharField(max_length=100)),
                ("stars", models.CharField(max_length=50)),
                ("raw", models.JSONField()),
            ],
        ),
    ]
