# Generated by Django 4.1.2 on 2022-10-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("okra", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="okrareviews",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
